# -*- coding: utf-8 -*-
"""Bank_Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZNKjok8jN3F_z3QNOubsy4Xd-NBGDFw-

# **Loading the libraries**
"""

import pandas as pd
import numpy as np

"""# **Step 1 - Loading the dataset**"""

df = pd.read_csv("/content/Banking_Fraud_Dataset.csv")
df

"""# Step 2 -**Understanding** **the** **dataset**"""

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.columns

df["Is_Fraud"].value_counts()

df["Previous_Fraud"].value_counts()

"""# **Step 3 - Cleaning the data**"""

df.isnull().sum()

df.drop_duplicates()

df = df.drop(columns ="Account_Age")

df = df.drop(columns = "Credit_Score")

df.dropna()

df

df.shape

df.info()

df.describe()

"""# **Step 4 - Data Visualization**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,5))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values Heatmap')
plt.show()

df["Transaction_Type"].value_counts().plot(kind="bar", title="Transaction Types")
plt.xlabel("Transaction types")
plt.ylabel("Count")
plt.show()

count_classes = df['Is_Fraud'].value_counts()

plt.figure(figsize=(6,4))
sns.barplot(x=count_classes.index, y=count_classes.values)

plt.title('Fraud vs Normal Transactions')
plt.xlabel('Class')
plt.ylabel('Count')

plt.xticks([0,1], ['Normal', 'Fraud'])
plt.show()

fraud_counts = df['Is_Fraud'].value_counts()

labels = ['Normal', 'Fraud']

plt.figure(figsize=(4,4))

plt.pie(
    fraud_counts,
    labels=labels,
    autopct='%1.2f%%',
    startangle=90
)

plt.title('Fraud Percentage')
plt.show()

plt.figure(figsize=(10,5))

sns.histplot(df['Transaction_Amount'], bins=50, kde=True)

plt.title('Transaction Amount Distribution')
plt.xlabel('Amount')
plt.ylabel('Frequency')

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x='Is_Fraud', y='Transaction_Amount', data=df)

plt.title('Fraud vs Normal Amount Distribution')
plt.xticks([0,1], ['Normal', 'Fraud'])
plt.show()

numeric_df = df.select_dtypes(include=['int64', 'float64'])

corr_matrix = numeric_df.corr()
plt.figure(figsize=(8,6))

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='coolwarm',
    fmt='.2f',
    linewidths=0.5
)

plt.title('Correlation Heatmap of Banking Fraud Dataset')
plt.show()

"""# **Step 5 - Model Training and Evaluation**"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

df.dtypes

# Create encoder
le = LabelEncoder()

# Convert all object columns
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = le.fit_transform(df[column])

df.dtypes

numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns

numeric_columns = numeric_columns.drop('Is_Fraud')

scaler = StandardScaler()

df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

X = df.drop('Is_Fraud', axis=1)

y = df['Is_Fraud']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

fraud = len(y_train[y_train == 1])

normal = len(y_train[y_train == 0])

scale_weight = normal / fraud

print(scale_weight)

"""# XGBoost"""

!pip install xgboost
!pip install shap
!pip install tensorflow

from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    scale_pos_weight=scale_weight,
    eval_metric='logloss',
    random_state=42
)

xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title('Confusion Matrix')

plt.xlabel('Predicted')
plt.ylabel('Actual')

plt.show()

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam

input_dim = X_train.shape[1]

encoding_dim = 14

input_layer = Input(shape=(input_dim,))

encoder = Dense(32, activation='relu')(input_layer)

encoder = Dense(encoding_dim, activation='relu')(encoder)

decoder = Dense(32, activation='relu')(encoder)

decoder = Dense(input_dim, activation='sigmoid')(decoder)

autoencoder = Model(
    inputs=input_layer,
    outputs=decoder
)

autoencoder.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mse'
)

X_train_normal = X_train[y_train == 0]

autoencoder.fit(
    X_train_normal,
    X_train_normal,
    epochs=20,
    batch_size=64,
    validation_split=0.2,
    shuffle=True
)

reconstructions = autoencoder.predict(X_test)

mse = np.mean(
    np.power(X_test - reconstructions, 2),
    axis=1
)

error_df = pd.DataFrame({
    'Reconstruction_error': mse,
    'True_class': y_test
})

plt.figure(figsize=(10,6))

sns.histplot(
    data=error_df,
    x='Reconstruction_error',
    hue='True_class',
    bins=50
)

plt.title('Reconstruction Error Distribution')

plt.show()

threshold = np.percentile(mse, 95)

anomaly_predictions = (mse > threshold).astype(int)

import shap

explainer = shap.TreeExplainer(xgb_model)

shap_values = explainer.shap_values(X_test)

shap.summary_plot(
    shap_values,
    X_test
)

"""## Customers with previous fraud history are more likely to commit fraud again."""

shap.summary_plot(
    shap_values,
    X_test,
    plot_type='bar'
)